development:
  adapter: postgresql
  encoding: unicode
  database: mtg_project
  pool: 5
  username: mtg_admin
  password: 12tybnH

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1
